version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/dependabot-dockerfiles/pihole"
    schedule:
      interval: "weekly"
      timezone: "America/New_York"
  - package-ecosystem: "docker"
    directory: "/dependabot-dockerfiles/unbound"
    schedule:
      interval: "weekly"
      timezone: "America/New_York"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "America/New_York"
