version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/dependabot-dockerfiles/pihole"
    schedule:
      interval: "daily"
      time: "22:00"
      timezone: "America/New_York"
  - package-ecosystem: "docker"
    directory: "/dependabot-dockerfiles/unbound"
    schedule:
      interval: "daily"
      time: "22:30"
      timezone: "America/New_York"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "America/New_York"
