version: "3.9"

services:
  unbound:
    network_mode: "host"
    environment:
      ALLOWED_SUBNET: 192.168.0.0\/16
  pihole:
    network_mode: "host"
    environment:
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: 127.0.0.1#5053
