version: "3.9"

services:
  unbound:
    image: ${UNBOUND_IMAGE}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  pihole:
    image: ${PIHOLE_IMAGE}
    depends_on:
      unbound:
        condition: service_started
    environment:
      TZ: America/New_York
      DNSSEC: "true"
      WEB_PORT: "62080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    # Query rate limit not configurable via env vars yet
    entrypoint: ["/bin/bash", "-c", "echo RATE_LIMIT=0/0 >> /etc/pihole/pihole-FTL.conf && /s6-init"]
