version: '3'

env:
  DOCKER_REPOSITORY: johnsprinkle
  DOCKER_IMAGE_NAME: unbound
  DOCKER_CONTAINER_NAME: unbound
  ALLOWED_SUBNET: "172.20.0.0\\/16" #Escaped '/' for sed to do a replacement

tasks:
  install-go:
    cmds:
      - brew install go
      - brew install golangci-lint

  format:
    cmds:
      - go mod tidy
      - go fmt ./...

  lint:
    cmds:
      - golangci-lint run
  default:
    deps:
      - task: echo_sth
        vars: {TEXT: "before 1"}

  start:
    cmds:
      - |
        UNBOUND_IMAGE=$(cat dependabot-dockerfiles/unbound/Dockerfile | cut -d ' ' -f 2) \
        PIHOLE_IMAGE=$(cat dependabot-dockerfiles/pihole/Dockerfile | cut -d ' ' -f 2) \
        PIHOLE_HOST_PORT=${PIHOLE_HOST_PORT:-5553} \
        docker-compose -p dns-ci -f docker-compose.yml -f docker-compose.bridge-networking.yml up -d 

  stop:
    cmds:
      - docker-compose -p dns-ci down

  test:
    cmds:
      - go clean -testcache
      - export PIHOLE_HOST_PORT=${PIHOLE_HOST_PORT:-5553} && go test -v ./...

  package:
    cmds:
      - tar -czvf dns-services.tar.gz *.sh docker-compose*.yml dependabot-dockerfiles

  pre:
    cmds:
      - task: format
      - task: lint
      - task: start
      - task: test
      - task: stop
      - task: package
