name: CI Processes

on:
  push:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.actor != 'dependabot[bot]') || (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.actor != 'dependabot[bot]') || (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]')}}
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: task start test stop
      - name: Package
        run: task package
      - name: Upload
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v2
        with:
          name: dns-services.tar.gz
          path: dns-services.tar.gz
      - name: Update 'latest' release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: h release upload latest --clobber dns-services.tar.gz
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  bump-dependencies:
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && github.ref != 'refs/heads/main' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'pihole/pihole') || contains(steps.metadata.outputs.dependency-names, 'johnsprinkle/unbound')}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
